export const resumeData = {
  name: "Arjit Gupta",
  title: "Software Engineer",
  location:
    "New Power Packs, W. No. 17, Link Road, Omara Morh, Udhampur, J&K - 182101",
  contacts: {
    phone: "+91-90860-74999",
    email: "arjitg36@gmail.com",
    linkedin: "https://www.linkedin.com/in/arjit-gupta-120741223",
    github: "https://github.com/lhtarjit",
    portfolio: "https://arjit-full-stack-portfolio-tm1p.vercel.app",
  },
  resumeUrl: "/Resume.pdf",
  summary:
    "I design and build performant web applications with a focus on clear UX and maintainable code. I specialise in React & Node.js and ship pragmatic solutions that scale.",
  skills: {
    highlighted: [
      "React.js",
      "Next.js",
      "TypeScript",
      "JavaScript (ES6+)",
      "Node.js",
      "Express.js",
      "REST APIs",
      "GraphQL",
      "Tailwind CSS",
      "Material UI",
      "Redux Toolkit",
      "React Hook Form",
      "MongoDB",
      "Socket.io",
      "JWT Authentication",
      "Core Web Vitals",
      "WCAG 2.1",
    ],
    categories: [
      {
        title: "Languages",
        items: ["JavaScript (ES6+)", "TypeScript", "HTML5", "CSS3"],
      },
      {
        title: "Frontend Frameworks & Libraries",
        items: [
          "React.js",
          "Next.js",
          "Redux Toolkit",
          "React Hook Form",
          "Tailwind CSS",
          "Material UI",
          "Bootstrap",
          "Styled Components",
          "SCSS/Sass",
          "Framer Motion",
        ],
      },
      {
        title: "Backend & APIs",
        items: ["Node.js", "Express.js", "REST APIs", "GraphQL", "Axios"],
      },
      {
        title: "Frontend Architecture",
        items: [
          "Component-Driven Development",
          "State Management",
          "Responsive Design",
          "Server-Side Rendering (SSR)",
          "Reusable Component Architecture",
          "Code Splitting",
          "Lazy Loading",
          "JWT Authentication",
        ],
      },
      {
        title: "Performance, SEO & Accessibility",
        items: [
          "Core Web Vitals",
          "Technical SEO",
          "Dynamic Sitemap",
          "Robots.txt",
          "Image & Bundle Optimisation",
          "Semantic HTML",
          "WCAG 2.1",
          "ARIA",
          "Keyboard Navigation",
        ],
      },
      {
        title: "Tools & Integrations",
        items: [
          "VS Code",
          "Cursor",
          "Postman",
          "Jira",
          "Confluence",
          "Figma",
          "Retool",
          "Puck CMS",
          "Google Tag Manager (GTM)",
          "Socket.io",
          "Agile/Scrum",
        ],
      },
      {
        title: "Testing & Code Quality",
        items: [
          "React Testing Library",
          "SonarQube",
          "ESLint",
          "Prettier",
          "Husky",
        ],
      },
      {
        title: "Build, Deploy & Databases",
        items: [
          "Webpack",
          "Vite",
          "Babel",
          "npm",
          "Yarn",
          "Git",
          "GitHub",
          "Bitbucket",
          "CI/CD",
          "Docker",
          "Vercel",
          "Netlify",
          "MongoDB",
          "MongoDB Compass",
          "8Base",
        ],
      },
    ],
    strengths: [
      "Creative problem solver — exceptional problem-solving skills with an innovative approach to challenges.",
      "Effective team player — strong collaborator in dynamic environments with cross-functional teams.",
      "Continuous learner — committed to learning and implementing cutting-edge technologies.",
    ],
  },
  experience: [
    {
      role: "Frontend Engineer",
      company: "Mobikasa Pvt. Ltd.",
      location: "Delhi, India",
      period: "June 2025 – July 2026",
      bullets: [
        "Developed and maintained BoxFo, a multi-portal SaaS platform (Admin, Partner, Customer) for virtual mailbox, mail forwarding, and luggage storage services.",
        "Delivered end-to-end modules including customer onboarding, KYC verification, virtual mailbox management, mail processing workflows, subscription lifecycle, wallet & payment systems, and role-based administration.",
        "Built a drag-and-drop page builder using Puck CMS, enabling non-technical users to create and manage dynamic marketing pages through reusable visual components.",
        "Integrated Stripe, BlueNotary, Socket.io, Google Maps and implemented Google Tag Manager (GTM) with custom event tracking, conversion tracking, and UTM/session analytics.",
        "Enhanced application performance through lazy loading, code splitting, optimised API interactions, reusable component architecture, responsive design, and WCAG-compliant interfaces.",
        "Implemented secure authentication, middleware-based route protection, session and UTM tracking, cookie consent management, and event analytics for user behaviour and marketing attribution.",
      ],
    },
    {
      role: "JavaScript Developer / MERN",
      company: "Solvative Pvt. Ltd.",
      location: "Ahmedabad, India",
      period: "Mar 2024 – May 2025",
      bullets: [
        "Engineered UI fixes and performance improvements across an enterprise insurance portal — reduced load time and improved stability.",
        "Introduced TypeScript patterns and code-review practices to increase maintainability.",
        "Partnered with backend and QA to deliver production-ready releases on time.",
      ],
    },
    {
      role: "Software Developer",
      company: "Leeway Hertz Pvt. Ltd.",
      location: "Gurgaon, India",
      period: "Mar 2022 – Jan 2024",
      bullets: [
        "Built reusable component libraries used across multiple client projects.",
        "Delivered polished interfaces for Blockchain & AI projects with an emphasis on UX and reliability.",
        "Sole frontend developer for YourNFTGuru — a platform for creating and selling NFTs — building two portals with React, Tailwind CSS, and Material UI.",
        "Integrated Leap AI to generate NFT images and multiple APIs for seamless communication with backend services.",
        "Implemented Redux for state management, ensuring accurate tracking of tokens deducted for each function and guaranteeing a fully responsive design.",
      ],
    },
  ],
  projects: [
    {
      name: "BoxFo",
      period: "June 2025 – July 2026",
      link: "https://boxfo.com",
      tech: [
        "Next.js",
        "TypeScript",
        "Puck CMS",
        "Stripe",
        "Socket.io",
        "GTM",
        "Tailwind CSS",
        "MongoDB",
        "JWT",
        "Role-Based Access Control",
      ],
      image: "/images/projects/boxfo.jpg",
      highlights: [
        "Developed and maintained a multi-portal SaaS platform (Admin, Partner, Customer) for virtual mailbox, mail forwarding, and luggage storage services.",
        "Delivered end-to-end modules including customer onboarding, KYC verification, virtual mailbox management, mail processing workflows, subscription lifecycle, wallet & payment systems, and role-based administration.",
        "Built a drag-and-drop page builder using Puck CMS for dynamic marketing pages through reusable visual components.",
        "Integrated Stripe, BlueNotary, Socket.io, Google Maps and implemented GTM with custom event tracking, conversion tracking, and UTM/session analytics.",
        "Enhanced performance through lazy loading, code splitting, optimised API interactions, and WCAG-compliant responsive interfaces.",
        "Implemented secure authentication, middleware-based route protection, session tracking, cookie consent management, and event analytics.",
      ],
    },
    {
      name: "Stock Management System",
      period: "Mar 2025 – Present",
      link: "https://stock-management-system-xi.vercel.app/",
      tech: [
        "Next.js",
        "Express.js",
        "MongoDB",
        "Node.js",
        "JWT",
        "Tailwind CSS",
        "SheetJS",
      ],
      image: "/images/projects/sms.jpg",
      highlights: [
        "Developed a full-stack stock management app for retail shopkeepers with secure role-based JWT authentication.",
        "Implemented Excel (SheetJS) upload with server-side validation, preventing data inconsistencies.",
        "Designed QR code generation & scanning for instant stock retrieval without manual search.",
        "Integrated real-time search with efficient pagination for quick access to large datasets.",
        "Optimized MongoDB queries and indexing to handle thousands of records seamlessly.",
        "Enhanced user experience with React Toastify notifications for key actions.",
      ],
    },
    {
      name: "Pacific Life — Insurance Portal",
      period: "Mar 2024 – May 2025",
      link: "#",
      tech: ["React", "TypeScript"],
      image: "/images/projects/pacificlife.jpg",
      highlights: [
        "Insurance project involving React development across multiple portals.",
        "Successfully resolved numerous critical and non-critical bugs, improving overall stability and performance.",
        "Improved application quality through code reviews and refactoring for maintainability.",
        "Ensured fully responsive designs for optimal multi-device user experiences.",
        "Collaborated closely with design and backend teams for a seamless, intuitive interface.",
      ],
    },
    {
      name: "YourNFTGuru — Creator & Admin Portals",
      period: "Aug 2023 – Dec 2023",
      link: "https://dev1-qa.yournft.guru/",
      secondaryLink: "https://qa-admin-webapp.yournft.guru/",
      tech: ["React", "Tailwind CSS", "Redux", "Material UI", "Leap AI"],
      image: "/images/projects/yournftguru.jpg",
      highlights: [
        "Sole frontend developer for both Creator & Admin portals, handling end-to-end UI development.",
        "Integrated Leap AI to auto-generate NFT images, enhancing creative capabilities.",
        "Built robust Redux-based state management for token deduction tracking.",
        "Integrated APIs for CRUD operations with secure authentication.",
        "Delivered fully responsive design for mobile, tablet, and desktop.",
        "Implemented reusable form components with validation for a smoother UX.",
      ],
    },
    {
      name: "UNO Test Prep",
      period: "Jul 2023 – Aug 2023",
      link: "https://unotestprep.com/",
      tech: ["React", "Tailwind CSS", "PhonePe API"],
      image: "/images/projects/unotestprep.jpg",
      highlights: [
        "Enhanced coaching platform's digital payment experience by integrating PhonePe gateway.",
        "Developed a responsive dashboard for students to manage test schedules and payments.",
        "Collaborated with backend team to ensure secure transaction flow.",
        "Streamlined UI elements for faster onboarding and improved navigation.",
        "Improved overall site speed and reduced load time by optimizing components.",
      ],
    },
    {
      name: "ZBrain.AI",
      period: "Mar 2023 – Jul 2023",
      link: "https://app.zbrain.ai/",
      tech: ["React", "Tailwind CSS"],
      image: "/images/projects/zbrain.jpg",
      highlights: [
        "Built fully responsive sign-in/signup flow with modern UI patterns.",
        "Implemented dynamic tables and lists with pagination for large data sets.",
        "Developed drag-and-drop file upload with progress indicators.",
        "Designed reusable components to speed up development across the app.",
        "Collaborated with product managers to refine UX flows.",
        "Optimized rendering performance using memoization and React hooks.",
      ],
    },
  ],
  education: [
    {
      degree: "B.Tech — Electronics & Communication",
      school: "Chandigarh Group of Colleges",
      location: "Chandigarh",
      period: "Aug 2017 – May 2021",
    },
    {
      degree: "Intermediate — Science",
      school: "Kendriya Vidyalaya No. 1",
      location: "Udhampur, J&K",
      period: "Apr 2015 – Mar 2017",
    },
    {
      degree: "Matriculation",
      school: "Kendriya Vidyalaya No. 1",
      location: "Udhampur, J&K",
      period: "Apr 2014 – Mar 2015",
    },
  ],
  certifications: [
    // HackerRank Certificates
    {
      certificate: "Frontend Developer (React)",
      institute: "HackerRank",
      level: "Verified Role",
      date: "2025-05-24",
      image: "/images/certificates/frontend-developer-react-certificate.jpg",
    },
    {
      certificate: "JavaScript",
      institute: "HackerRank",
      level: "Intermediate",
      date: "2025-05-26",
      image: "/images/certificates/javascript-intermediate-certificate.jpg",
    },
    {
      certificate: "JavaScript",
      institute: "HackerRank",
      level: "Basic",
      date: "2025-05-24",
      image: "/images/certificates/javascript-basic-certificate.jpg",
    },
    {
      certificate: "React",
      institute: "HackerRank",
      level: "Basic",
      date: "2025-05-26",
      image: "/images/certificates/react-basic-certificate.jpg",
    },
    {
      certificate: "Rest API",
      institute: "HackerRank",
      level: "Intermediate",
      date: "2025-05-26",
      image: "/images/certificates/rest-api-intermediate-certificate.jpg",
    },
    {
      certificate: "Cascading Style Sheets (CSS)",
      institute: "HackerRank",
      level: "Basic",
      date: "2025-05-26",
      image: "/images/certificates/css-basic-certificate.jpg",
    },
    {
      certificate: "Problem Solving",
      institute: "HackerRank",
      level: "Basic",
      date: "2025-05-26",
      image: "/images/certificates/problem-solving-basic-certificate.jpg",
    },
    {
      certificate: "Problem Solving",
      institute: "HackerRank",
      level: "Intermediate",
      date: "2025-05-26",
      image:
        "/images/certificates/problem-solving-intermediate-certificate.jpg",
    },

    // Great Learning Certificates (example)
    {
      certificate: "React JS — Certification for React Development",
      institute: "Great Learning",
      level: "Beginner",
      date: "2024-03-15",
      image: "/images/certificates/React-JS-Tutorial.jpg",
    },
    {
      certificate: "JavaScript — Certification for JavaScript Fundamentals",
      institute: "Great Learning",
      date: "2023-11-05",
      level: "Beginner",
      image: "/images/certificates/javascript-fundamentals.jpg",
    },
    // INFOWIZ Certificates
    {
      certificate: "6 Months Training in Python",
      institute: "INFOWIZ Pvt. Ltd.",
      level: "Training",
      date: "2021-01-01",
      image: "/images/certificates/python-certification.jpg",
    },
  ],
};
