export const resumeData = {
  name: "Arjit Gupta",
  title: "MERN Stack Developer",
  location: "Udhampur, J&K, India",
  contacts: {
    phone: "+91-90860-74999",
    email: "arjitg36@gmail.com",
    linkedin: "https://www.linkedin.com/in/arjit-gupta-120741223",
    github: "https://github.com/lhtarjit",
  },
  resumeUrl: "/Resume.pdf",
  summary:
    "I design and build performant web applications with a focus on clear UX and maintainable code. I specialise in React & Node.js and ship pragmatic solutions that scale.",
  skills: {
    languagesAndFrameworks: [
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Node.js",
      "Express.js",
      "HTML5",
      "CSS3",
      "Tailwind CSS",
    ],
    tools: ["Git", "VSCode", "Postman", "MongoDB Compass", "Jira"],
    databases: ["MongoDB"],
    strengths: ["Product-minded", "Collaborative", "Performance-first"],
  },
  experience: [
    {
      role: "Front-End Ninja / MERN",
      company: "Mobikasa Pvt. Ltd.",
      location: "New Delhi",
      period: "June 2025 – Working",
      bullets: [
        "Developed and maintained **Boxfo**, a multi-portal platform (Admin, Vendor, Customer) with role-based access control and secure module-level permissions.",
        "Enhanced UI and performance across an enterprise insurance portal, reducing load times and improving stability.",
        "Introduced TypeScript patterns and best practices, improving code maintainability and scalability.",
        "Collaborated closely with backend and QA teams to deliver production-ready releases on schedule.",
        "Implemented responsive, user-friendly interfaces with smooth workflows and dynamic content handling.",
      ],
    },
    {
      role: "JavaScript Developer / MERN",
      company: "Solvative Pvt. Ltd.",
      location: "Ahmedabad",
      period: "Mar 2024 – May 2025",
      bullets: [
        "Engineered UI fixes and performance improvements across an enterprise insurance portal — reduced load time and improved stability.",
        "Introduced TypeScript patterns and code-review practices to increase maintainability.",
        "Partnered with backend and QA to deliver production-ready releases on time.",
      ],
    },
    {
      role: "React Developer",
      company: "LeewayHertz Pvt. Ltd.",
      location: "Gurgaon",
      period: "Mar 2022 – Jan 2024",
      bullets: [
        "Built reusable component libraries used across multiple client projects.",
        "Delivered polished interfaces for Blockchain & AI projects with an emphasis on UX and reliability.",
      ],
    },
  ],
  projects: [
    {
      name: "Boxfo",
      period: "June 2025 – Present",
      link: "#",
      tech: [
        "Next.js",
        "MongoDB",
        "JWT",
        "Tailwind CSS",
        "Role-Based Access Control",
      ],
      image: "/images/projects/boxfo.jpg",
      highlights: [
        "Developed and maintained a multi-portal platform (Admin, Vendor, Customer) with role-based access control and secure module-level permissions.",
        "Enhanced UI and performance across an enterprise insurance portal, reducing load times and improving stability.",
        "Introduced TypeScript patterns and best practices, improving code maintainability and scalability.",
        "Collaborated closely with backend and QA teams to deliver production-ready releases on schedule.",
        "Implemented responsive, user-friendly interfaces with smooth workflows and dynamic content handling.",
      ],
    },
    {
      name: "Stock Management System",
      period: "Mar 2025 – Present",
      link: "https://stock-management-system-xi.vercel.app/",
      tech: [
        "Next.js",
        "Express.js",
        "MongoDB",
        "Node.js",
        "JWT",
        "Tailwind CSS",
        "SheetJS",
      ],
      image: "/images/projects/sms.jpg",
      highlights: [
        "Developed a full-stack stock management app for retail shopkeepers with secure role-based JWT authentication.",
        "Implemented Excel (SheetJS) upload with server-side validation, preventing data inconsistencies.",
        "Designed QR code generation & scanning for instant stock retrieval without manual search.",
        "Integrated real-time search with efficient pagination for quick access to large datasets.",
        "Optimized MongoDB queries and indexing to handle thousands of records seamlessly.",
        "Enhanced user experience with React Toastify notifications for key actions.",
      ],
    },
    {
      name: "Pacific Life — Insurance Portal",
      period: "Mar 2024 – Jan 2025",
      link: "#",
      tech: ["React", "TypeScript"],
      image: "/images/projects/pacificlife.jpg",
      highlights: [
        "Collaborated across teams to maintain and enhance 3 React TypeScript portals for insurance services.",
        "Resolved critical UI and functional bugs, improving portal stability and performance.",
        "Refactored components and introduced reusable patterns for maintainable code.",
        "Ensured full responsiveness and cross-browser compatibility.",
        "Improved accessibility compliance, aligning with WCAG standards.",
        "Worked closely with QA to ensure bug-free production releases.",
      ],
    },
    {
      name: "YourNFTGuru — Creator & Admin Portals",
      period: "Aug 2023 – Dec 2023",
      link: "https://dev1-qa.yournft.guru/",
      secondaryLink: "https://qa-admin-webapp.yournft.guru/",
      tech: ["React", "Tailwind CSS", "Redux", "Material UI", "Leap AI"],
      image: "/images/projects/yournftguru.jpg",
      highlights: [
        "Sole frontend developer for both Creator & Admin portals, handling end-to-end UI development.",
        "Integrated Leap AI to auto-generate NFT images, enhancing creative capabilities.",
        "Built robust Redux-based state management for token deduction tracking.",
        "Integrated APIs for CRUD operations with secure authentication.",
        "Delivered fully responsive design for mobile, tablet, and desktop.",
        "Implemented reusable form components with validation for a smoother UX.",
      ],
    },
    {
      name: "UNO Test Prep",
      period: "Jul 2023 – Aug 2023",
      link: "#",
      tech: ["React", "Tailwind CSS", "PhonePe API"],
      image: "/images/projects/unotestprep.jpg",
      highlights: [
        "Enhanced coaching platform’s digital payment experience by integrating PhonePe gateway.",
        "Developed a responsive dashboard for students to manage test schedules and payments.",
        "Collaborated with backend team to ensure secure transaction flow.",
        "Streamlined UI elements for faster onboarding and improved navigation.",
        "Improved overall site speed and reduced load time by optimizing components.",
      ],
    },
    {
      name: "ZBrain.AI",
      period: "Mar 2023 – Jul 2023",
      link: "#",
      tech: ["React", "Tailwind CSS"],
      image: "/images/projects/zbrain.jpg",
      highlights: [
        "Built fully responsive sign-in/signup flow with modern UI patterns.",
        "Implemented dynamic tables and lists with pagination for large data sets.",
        "Developed drag-and-drop file upload with progress indicators.",
        "Designed reusable components to speed up development across the app.",
        "Collaborated with product managers to refine UX flows.",
        "Optimized rendering performance using memoization and React hooks.",
      ],
    },
  ],
  education: [
    {
      degree: "B.Tech — Electronics & Communication",
      school: "Chandigarh Group of Colleges",
      location: "Punjab",
      period: "Aug 2017 – May 2021",
    },
    {
      degree: "Intermediate — Science",
      school: "Kendriya Vidyalaya No. 1",
      location: "Udhampur, J&K",
      period: "Apr 2015 – Mar 2017",
    },
    {
      degree: "Matriculation",
      school: "Kendriya Vidyalaya No. 1",
      location: "Udhampur, J&K",
      period: "Apr 2014 – Mar 2015",
    },
  ],
  certifications: [
    // HackerRank Certificates
    {
      certificate: "Frontend Developer (React)",
      institute: "HackerRank",
      level: "Verified Role",
      date: "2025-05-24",
      image: "/images/certificates/frontend-developer-react-certificate.jpg",
    },
    {
      certificate: "JavaScript",
      institute: "HackerRank",
      level: "Intermediate",
      date: "2025-05-26",
      image: "/images/certificates/javascript-intermediate-certificate.jpg",
    },
    {
      certificate: "JavaScript",
      institute: "HackerRank",
      level: "Basic",
      date: "2025-05-24",
      image: "/images/certificates/javascript-basic-certificate.jpg",
    },
    {
      certificate: "React",
      institute: "HackerRank",
      level: "Basic",
      date: "2025-05-26",
      image: "/images/certificates/react-basic-certificate.jpg",
    },
    {
      certificate: "Rest API",
      institute: "HackerRank",
      level: "Intermediate",
      date: "2025-05-26",
      image: "/images/certificates/rest-api-intermediate-certificate.jpg",
    },
    {
      certificate: "Cascading Style Sheets (CSS)",
      institute: "HackerRank",
      level: "Basic",
      date: "2025-05-26",
      image: "/images/certificates/css-basic-certificate.jpg",
    },
    {
      certificate: "Problem Solving",
      institute: "HackerRank",
      level: "Basic",
      date: "2025-05-26",
      image: "/images/certificates/problem-solving-basic-certificate.jpg",
    },
    {
      certificate: "Problem Solving",
      institute: "HackerRank",
      level: "Intermediate",
      date: "2025-05-26",
      image:
        "/images/certificates/problem-solving-intermediate-certificate.jpg",
    },

    // Great Learning Certificates (example)
    {
      certificate: "React JS — Certification for React Development",
      institute: "Great Learning",
      level: "Beginner",
      date: "2024-03-15",
      image: "/images/certificates/React-JS-Tutorial.jpg",
    },
    {
      certificate: "JavaScript — Certification for JavaScript Fundamentals",
      institute: "Great Learning",
      date: "2023-11-05",
      level: "Beginner",
      image: "/images/certificates/dsa.png",
    },
  ],
};
